[package]
name = "adventofcode"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
counter = "0.5.2"
either = "1.6.1"
itertools = "0.10.1"
num = "0.4.0"
regex = "1.5.4"
streaming-stats = "0.2.3"
